language: python
sudo: required
dist: xenial
services:
  - xvfb

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

cache: pip

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pip install PyQt5 PySide2

script:
  - QT_API=PyQt5 pipenv run py.test --forked -v
  - QT_API=PySide2 pipenv run py.test --forked -v
