environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python39"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pip install PyQt5 PySide2
  # FIX: colorama not installed by pipenv
  - pipenv run pip install colorama

build: off

test_script:
  - set QT_API=PyQt5&& pipenv run py.test -v 
  - set QT_API=PySide2&& pipenv run py.test -v 
