name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
          enable-cache: true

      - name: Build qasync
        run: uv build

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          allowUpdates: true
          generateReleaseNotes: true
          token: ${{ github.token }}

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish
